// Copyright 2026 James Cunningham
// SPDX-License-Identifier: BSD-3-Clause
//
// Use of this source code is governed by a BSD-style license that can be found
// in the LICENSE file or at https://opensource.org/license/BSD-3-clause

package known

// References:
//   - linux/Documentation/netlink/specs
//   - a lot kernel sources
//   - googling
var families = []Family{
	{
		Name: "binder",
		Desc: "Binder interface over generic netlink",
		Cmds: []Cmd{
			{Cmd: 1, Name: "BINDER_CMD_REPORT"},
		},
	},
	{
		Name: "devlink",
		Desc: "Partial family for Devlink.",
		Cmds: []Cmd{
			{Cmd: 1, Name: "DEVLINK_CMD_GET"},
			{Cmd: 2, Name: "DEVLINK_CMD_SET"},
			{Cmd: 3, Name: "DEVLINK_CMD_NEW"},
			{Cmd: 4, Name: "DEVLINK_CMD_DEL"},
			{Cmd: 5, Name: "DEVLINK_CMD_PORT_GET"},
			{Cmd: 6, Name: "DEVLINK_CMD_PORT_SET"},
			{Cmd: 7, Name: "DEVLINK_CMD_PORT_NEW"},
			{Cmd: 8, Name: "DEVLINK_CMD_PORT_DEL"},
			{Cmd: 9, Name: "DEVLINK_CMD_PORT_SPLIT"},
			{Cmd: 10, Name: "DEVLINK_CMD_PORT_UNSPLIT"},
			{Cmd: 11, Name: "DEVLINK_CMD_SB_GET"},
			{Cmd: 12, Name: "DEVLINK_CMD_SB_SET"},
			{Cmd: 13, Name: "DEVLINK_CMD_SB_NEW"},
			{Cmd: 14, Name: "DEVLINK_CMD_SB_DEL"},
			{Cmd: 15, Name: "DEVLINK_CMD_SB_POOL_GET"},
			{Cmd: 16, Name: "DEVLINK_CMD_SB_POOL_SET"},
			{Cmd: 17, Name: "DEVLINK_CMD_SB_POOL_NEW"},
			{Cmd: 18, Name: "DEVLINK_CMD_SB_POOL_DEL"},
			{Cmd: 19, Name: "DEVLINK_CMD_SB_PORT_POOL_GET"},
			{Cmd: 20, Name: "DEVLINK_CMD_SB_PORT_POOL_SET"},
			{Cmd: 21, Name: "DEVLINK_CMD_SB_PORT_POOL_NEW"},
			{Cmd: 22, Name: "DEVLINK_CMD_SB_PORT_POOL_DEL"},
			{Cmd: 23, Name: "DEVLINK_CMD_SB_TC_POOL_BIND_GET"},
			{Cmd: 24, Name: "DEVLINK_CMD_SB_TC_POOL_BIND_SET"},
			{Cmd: 25, Name: "DEVLINK_CMD_SB_TC_POOL_BIND_NEW"},
			{Cmd: 26, Name: "DEVLINK_CMD_SB_TC_POOL_BIND_DEL"},
			{Cmd: 27, Name: "DEVLINK_CMD_SB_OCC_SNAPSHOT"},
			{Cmd: 28, Name: "DEVLINK_CMD_SB_OCC_MAX_CLEAR"},
			{Cmd: 29, Name: "DEVLINK_CMD_ESWITCH_GET"},
			{Cmd: 30, Name: "DEVLINK_CMD_ESWITCH_GET"},
			{Cmd: 31, Name: "DEVLINK_CMD_ESWITCH_SET"},
			{Cmd: 32, Name: "DEVLINK_CMD_ESWITCH_SET"},
			{Cmd: 33, Name: "DEVLINK_CMD_DPIPE_TABLE_GET"},
			{Cmd: 34, Name: "DEVLINK_CMD_DPIPE_ENTRIES_GET"},
			{Cmd: 35, Name: "DEVLINK_CMD_DPIPE_HEADERS_GET"},
			{Cmd: 36, Name: "DEVLINK_CMD_DPIPE_TABLE_COUNTERS_SET"},
			{Cmd: 37, Name: "DEVLINK_CMD_RESOURCE_SET"},
			{Cmd: 38, Name: "DEVLINK_CMD_RESOURCE_DUMP"},
			{Cmd: 39, Name: "DEVLINK_CMD_RELOAD"},
			{Cmd: 40, Name: "DEVLINK_CMD_PARAM_GET"},
			{Cmd: 41, Name: "DEVLINK_CMD_PARAM_SET"},
			{Cmd: 42, Name: "DEVLINK_CMD_PARAM_NEW"},
			{Cmd: 43, Name: "DEVLINK_CMD_PARAM_DEL"},
			{Cmd: 44, Name: "DEVLINK_CMD_REGION_GET"},
			{Cmd: 45, Name: "DEVLINK_CMD_REGION_SET"},
			{Cmd: 46, Name: "DEVLINK_CMD_REGION_NEW"},
			{Cmd: 47, Name: "DEVLINK_CMD_REGION_DEL"},
			{Cmd: 48, Name: "DEVLINK_CMD_REGION_READ"},
			{Cmd: 49, Name: "DEVLINK_CMD_PORT_PARAM_GET"},
			{Cmd: 50, Name: "DEVLINK_CMD_PORT_PARAM_SET"},
			{Cmd: 51, Name: "DEVLINK_CMD_PORT_PARAM_NEW"},
			{Cmd: 52, Name: "DEVLINK_CMD_PORT_PARAM_DEL"},
			{Cmd: 53, Name: "DEVLINK_CMD_INFO_GET"},
			{Cmd: 54, Name: "DEVLINK_CMD_HEALTH_REPORTER_GET"},
			{Cmd: 55, Name: "DEVLINK_CMD_HEALTH_REPORTER_SET"},
			{Cmd: 56, Name: "DEVLINK_CMD_HEALTH_REPORTER_RECOVER"},
			{Cmd: 57, Name: "DEVLINK_CMD_HEALTH_REPORTER_DIAGNOSE"},
			{Cmd: 58, Name: "DEVLINK_CMD_HEALTH_REPORTER_DUMP_GET"},
			{Cmd: 59, Name: "DEVLINK_CMD_HEALTH_REPORTER_DUMP_CLEAR"},
			{Cmd: 60, Name: "DEVLINK_CMD_FLASH_UPDATE"},
			{Cmd: 61, Name: "DEVLINK_CMD_FLASH_UPDATE_END"},
			{Cmd: 62, Name: "DEVLINK_CMD_FLASH_UPDATE_STATUS"},
			{Cmd: 63, Name: "DEVLINK_CMD_TRAP_GET"},
			{Cmd: 64, Name: "DEVLINK_CMD_TRAP_SET"},
			{Cmd: 65, Name: "DEVLINK_CMD_TRAP_NEW"},
			{Cmd: 66, Name: "DEVLINK_CMD_TRAP_DEL"},
			{Cmd: 67, Name: "DEVLINK_CMD_TRAP_GROUP_GET"},
			{Cmd: 68, Name: "DEVLINK_CMD_TRAP_GROUP_SET"},
			{Cmd: 69, Name: "DEVLINK_CMD_TRAP_GROUP_NEW"},
			{Cmd: 70, Name: "DEVLINK_CMD_TRAP_GROUP_DEL"},
			{Cmd: 71, Name: "DEVLINK_CMD_TRAP_POLICER_GET"},
			{Cmd: 72, Name: "DEVLINK_CMD_TRAP_POLICER_SET"},
			{Cmd: 73, Name: "DEVLINK_CMD_TRAP_POLICER_NEW"},
			{Cmd: 74, Name: "DEVLINK_CMD_TRAP_POLICER_DEL"},
			{Cmd: 75, Name: "DEVLINK_CMD_HEALTH_REPORTER_TEST"},
			{Cmd: 76, Name: "DEVLINK_CMD_RATE_GET"},
			{Cmd: 77, Name: "DEVLINK_CMD_RATE_SET"},
			{Cmd: 78, Name: "DEVLINK_CMD_RATE_NEW"},
			{Cmd: 79, Name: "DEVLINK_CMD_RATE_DEL"},
			{Cmd: 80, Name: "DEVLINK_CMD_LINECARD_GET"},
			{Cmd: 81, Name: "DEVLINK_CMD_LINECARD_SET"},
			{Cmd: 82, Name: "DEVLINK_CMD_LINECARD_NEW"},
			{Cmd: 83, Name: "DEVLINK_CMD_LINECARD_DEL"},
			{Cmd: 84, Name: "DEVLINK_CMD_SELFTESTS_GET"},
			{Cmd: 85, Name: "DEVLINK_CMD_SELFTESTS_RUN"},
			{Cmd: 86, Name: "DEVLINK_CMD_NOTIFY_FILTER_SET"},
		},
	},
	{
		Name: "ethtool",
		Desc: "Partial family for Ethtool Netlink.",
		Cmds: []Cmd{
			{Cmd: 0, Name: "ETHTOOL_MSG_KERNEL_NONE"},
			{Cmd: 1, Name: "ETHTOOL_MSG_STRSET_GET_REPLY"},
			{Cmd: 2, Name: "ETHTOOL_MSG_LINKINFO_GET_REPLY"},
			{Cmd: 3, Name: "ETHTOOL_MSG_LINKINFO_NTF"},
			{Cmd: 4, Name: "ETHTOOL_MSG_LINKMODES_GET_REPLY"},
			{Cmd: 5, Name: "ETHTOOL_MSG_LINKMODES_NTF"},
			{Cmd: 6, Name: "ETHTOOL_MSG_LINKSTATE_GET_REPLY"},
			{Cmd: 7, Name: "ETHTOOL_MSG_DEBUG_GET_REPLY"},
			{Cmd: 8, Name: "ETHTOOL_MSG_DEBUG_NTF"},
			{Cmd: 9, Name: "ETHTOOL_MSG_WOL_GET_REPLY"},
			{Cmd: 10, Name: "ETHTOOL_MSG_WOL_NTF"},
			{Cmd: 11, Name: "ETHTOOL_MSG_FEATURES_GET_REPLY"},
			{Cmd: 12, Name: "ETHTOOL_MSG_FEATURES_SET_REPLY"},
			{Cmd: 13, Name: "ETHTOOL_MSG_FEATURES_NTF"},
			{Cmd: 14, Name: "ETHTOOL_MSG_PRIVFLAGS_GET_REPLY"},
			{Cmd: 15, Name: "ETHTOOL_MSG_PRIVFLAGS_NTF"},
			{Cmd: 16, Name: "ETHTOOL_MSG_RINGS_GET_REPLY"},
			{Cmd: 17, Name: "ETHTOOL_MSG_RINGS_NTF"},
			{Cmd: 18, Name: "ETHTOOL_MSG_CHANNELS_GET_REPLY"},
			{Cmd: 19, Name: "ETHTOOL_MSG_CHANNELS_NTF"},
			{Cmd: 20, Name: "ETHTOOL_MSG_COALESCE_GET_REPLY"},
			{Cmd: 21, Name: "ETHTOOL_MSG_COALESCE_NTF"},
			{Cmd: 22, Name: "ETHTOOL_MSG_PAUSE_GET_REPLY"},
			{Cmd: 23, Name: "ETHTOOL_MSG_PAUSE_NTF"},
			{Cmd: 24, Name: "ETHTOOL_MSG_EEE_GET_REPLY"},
			{Cmd: 25, Name: "ETHTOOL_MSG_EEE_NTF"},
			{Cmd: 26, Name: "ETHTOOL_MSG_TSINFO_GET_REPLY"},
			{Cmd: 27, Name: "ETHTOOL_MSG_CABLE_TEST_NTF"},
			{Cmd: 28, Name: "ETHTOOL_MSG_CABLE_TEST_TDR_NTF"},
			{Cmd: 29, Name: "ETHTOOL_MSG_TUNNEL_INFO_GET_REPLY"},
			{Cmd: 30, Name: "ETHTOOL_MSG_FEC_GET_REPLY"},
			{Cmd: 31, Name: "ETHTOOL_MSG_FEC_NTF"},
			{Cmd: 32, Name: "ETHTOOL_MSG_MODULE_EEPROM_GET_REPLY"},
			{Cmd: 33, Name: "ETHTOOL_MSG_STATS_GET_REPLY"},
			{Cmd: 34, Name: "ETHTOOL_MSG_PHC_VCLOCKS_GET_REPLY"},
			{Cmd: 35, Name: "ETHTOOL_MSG_MODULE_GET_REPLY"},
			{Cmd: 36, Name: "ETHTOOL_MSG_MODULE_NTF"},
			{Cmd: 37, Name: "ETHTOOL_MSG_PSE_GET_REPLY"},
			{Cmd: 38, Name: "ETHTOOL_MSG_RSS_GET_REPLY"},
			{Cmd: 39, Name: "ETHTOOL_MSG_PLCA_GET_CFG_REPLY"},
			{Cmd: 40, Name: "ETHTOOL_MSG_PLCA_GET_STATUS_REPLY"},
			{Cmd: 41, Name: "ETHTOOL_MSG_PLCA_NTF"},
			{Cmd: 42, Name: "ETHTOOL_MSG_MM_GET_REPLY"},
			{Cmd: 43, Name: "ETHTOOL_MSG_MM_NTF"},
			{Cmd: 44, Name: "ETHTOOL_MSG_MODULE_FW_FLASH_NTF"},
			{Cmd: 45, Name: "ETHTOOL_MSG_PHY_GET_REPLY"},
			{Cmd: 46, Name: "ETHTOOL_MSG_PHY_NTF"},
			{Cmd: 47, Name: "ETHTOOL_MSG_TSCONFIG_GET_REPLY"},
			{Cmd: 48, Name: "ETHTOOL_MSG_TSCONFIG_SET_REPLY"},
			{Cmd: 49, Name: "ETHTOOL_MSG_PSE_NTF"},
			{Cmd: 50, Name: "ETHTOOL_MSG_RSS_NTF"},
			{Cmd: 51, Name: "ETHTOOL_MSG_RSS_CREATE_ACT_REPLY"},
			{Cmd: 52, Name: "ETHTOOL_MSG_RSS_CREATE_NTF"},
			{Cmd: 53, Name: "ETHTOOL_MSG_RSS_DELETE_NTF"},
			{Cmd: 54, Name: "ETHTOOL_MSG_MSE_GET_REPLY"},
		},
	},
	{
		Name: "handshake",
		Desc: "Netlink protocol to request a transport layer security handshake.",
		Cmds: []Cmd{
			{Cmd: 1, Name: "HANDSHAKE_CMD_READY"},
			{Cmd: 2, Name: "HANDSHAKE_CMD_ACCEPT"},
			{Cmd: 3, Name: "HANDSHAKE_CMD_DONE"},
		},
	},
	{
		Name: "IOAM6",
		Desc: "IPv6 In-situ OAM (IOAM)",
		Cmds: []Cmd{
			{Cmd: 1, Name: "IOAM6_CMD_ADD_NAMESPACE"},
			{Cmd: 2, Name: "IOAM6_CMD_DEL_NAMESPACE"},
			{Cmd: 3, Name: "IOAM6_CMD_DUMP_NAMESPACES"},
			{Cmd: 4, Name: "IOAM6_CMD_ADD_SCHEMA"},
			{Cmd: 5, Name: "IOAM6_CMD_DEL_SCHEMA"},
			{Cmd: 6, Name: "IOAM6_CMD_DUMP_SCHEMAS"},
			{Cmd: 7, Name: "IOAM6_CMD_NS_SET_SCHEMA"},
		},
	},
	{
		Name: "lockd",
		Desc: "lockd configuration over generic netlink",
		Cmds: []Cmd{
			{Cmd: 1, Name: "LOCKD_CMD_SERVER_SET"},
			{Cmd: 2, Name: "LOCKD_CMD_SERVER_GET"},
		},
	},
	{
		Name: "nbd",
		Desc: "Network Block Device is a Linux-originated lightweight block access protocol that allows one to export a block device to a client.", //nolint
		Cmds: []Cmd{
			{Cmd: 0, Name: "NBD_CMD_READ"},
			{Cmd: 1, Name: "NBD_CMD_WRITE"},
			{Cmd: 2, Name: "NBD_CMD_DISC"},
			{Cmd: 3, Name: "NBD_CMD_FLUSH"},
			{Cmd: 4, Name: "NBD_CMD_TRIM"},
			{Cmd: 6, Name: "NBD_CMD_WRITE_ZEROES"},
		},
	},
	{
		Name: "netdev",
		Desc: "netdev configuration over generic netlink.",
		Cmds: []Cmd{
			{Cmd: 1, Name: "NETDEV_CMD_DEV_GET"},
			{Cmd: 2, Name: "NETDEV_CMD_DEV_ADD_NTF"},
			{Cmd: 3, Name: "NETDEV_CMD_DEV_DEL_NTF"},
			{Cmd: 4, Name: "NETDEV_CMD_DEV_CHANGE_NTF"},
			{Cmd: 5, Name: "NETDEV_CMD_PAGE_POOL_GET"},
			{Cmd: 6, Name: "NETDEV_CMD_PAGE_POOL_ADD_NTF"},
			{Cmd: 7, Name: "NETDEV_CMD_PAGE_POOL_DEL_NTF"},
			{Cmd: 8, Name: "NETDEV_CMD_PAGE_POOL_CHANGE_NTF"},
			{Cmd: 9, Name: "NETDEV_CMD_PAGE_POOL_STATS_GET"},
			{Cmd: 10, Name: "NETDEV_CMD_QUEUE_GET"},
			{Cmd: 11, Name: "NETDEV_CMD_NAPI_GET"},
			{Cmd: 12, Name: "NETDEV_CMD_QSTATS_GET"},
			{Cmd: 13, Name: "NETDEV_CMD_BIND_RX"},
			{Cmd: 14, Name: "NETDEV_CMD_NAPI_SET"},
			{Cmd: 15, Name: "NETDEV_CMD_BIND_TX"},
			{Cmd: 16, Name: "NETDEV_CMD_QUEUE_CREATE"},
		},
	},
	{
		Name: "nfsd",
		Desc: "",
		Cmds: []Cmd{
			{Cmd: 1, Name: "NFSD_CMD_RPC_STATUS_GET"},
			{Cmd: 2, Name: "NFSD_CMD_THREADS_SET"},
			{Cmd: 3, Name: "NFSD_CMD_THREADS_GET"},
			{Cmd: 4, Name: "NFSD_CMD_VERSION_SET"},
			{Cmd: 5, Name: "NFSD_CMD_VERSION_GET"},
			{Cmd: 6, Name: "NFSD_CMD_LISTENER_SET"},
			{Cmd: 7, Name: "NFSD_CMD_LISTENER_GET"},
			{Cmd: 8, Name: "NFSD_CMD_POOL_MODE_SET"},
			{Cmd: 9, Name: "NFSD_CMD_POOL_MODE_GET"},
			{Cmd: 10, Name: "NFSD_CMD_CACHE_NOTIFY"},
			{Cmd: 11, Name: "NFSD_CMD_SVC_EXPORT_GET_REQS"},
			{Cmd: 12, Name: "NFSD_CMD_SVC_EXPORT_SET_REQS"},
			{Cmd: 13, Name: "NFSD_CMD_EXPKEY_GET_REQS"},
			{Cmd: 14, Name: "NFSD_CMD_EXPKEY_SET_REQS"},
			{Cmd: 15, Name: "NFSD_CMD_CACHE_FLUSH"},
			{Cmd: 16, Name: "NFSD_CMD_UNLOCK_IP"},
			{Cmd: 17, Name: "NFSD_CMD_UNLOCK_FILESYSTEM"},
			{Cmd: 18, Name: "NFSD_CMD_UNLOCK_EXPORT"},
		},
	},
	{
		Name: "nl80211",
		Desc: "Netlink API for 802.11 wireless devices",
		Cmds: []Cmd{
			{Cmd: 1, Name: "NL80211_CMD_GET_WIPHY"},
			{Cmd: 2, Name: "NL80211_CMD_SET_WIPHY"},
			{Cmd: 3, Name: "NL80211_CMD_NEW_WIPHY"},
			{Cmd: 4, Name: "NL80211_CMD_DEL_WIPHY"},
			{Cmd: 5, Name: "NL80211_CMD_GET_INTERFACE"},
			{Cmd: 6, Name: "NL80211_CMD_SET_INTERFACE"},
			{Cmd: 7, Name: "NL80211_CMD_NEW_INTERFACE"},
			{Cmd: 8, Name: "NL80211_CMD_DEL_INTERFACE"},
			{Cmd: 9, Name: "NL80211_CMD_GET_KEY"},
			{Cmd: 10, Name: "NL80211_CMD_SET_KEY"},
			{Cmd: 11, Name: "NL80211_CMD_NEW_KEY"},
			{Cmd: 12, Name: "NL80211_CMD_DEL_KEY"},
			{Cmd: 13, Name: "NL80211_CMD_GET_BEACON"},
			{Cmd: 14, Name: "NL80211_CMD_SET_BEACON"},
			{Cmd: 15, Name: "NL80211_CMD_START_AP"},
			{Cmd: 16, Name: "NL80211_CMD_STOP_AP"},
			{Cmd: 17, Name: "NL80211_CMD_GET_STATION"},
			{Cmd: 18, Name: "NL80211_CMD_SET_STATION"},
			{Cmd: 19, Name: "NL80211_CMD_NEW_STATION"},
			{Cmd: 20, Name: "NL80211_CMD_DEL_STATION"},
			{Cmd: 21, Name: "NL80211_CMD_GET_MPATH"},
			{Cmd: 22, Name: "NL80211_CMD_SET_MPATH"},
			{Cmd: 23, Name: "NL80211_CMD_NEW_MPATH"},
			{Cmd: 24, Name: "NL80211_CMD_DEL_MPATH"},
			{Cmd: 25, Name: "NL80211_CMD_SET_BSS"},
			{Cmd: 26, Name: "NL80211_CMD_SET_REG"},
			{Cmd: 27, Name: "NL80211_CMD_REQ_SET_REG"},
			{Cmd: 28, Name: "NL80211_CMD_GET_MESH_CONFIG"},
			{Cmd: 29, Name: "NL80211_CMD_SET_MESH_CONFIG"},
			{Cmd: 30, Name: "NL80211_CMD_SET_MGMT_EXTRA_IE"},
			{Cmd: 31, Name: "NL80211_CMD_GET_REG"},
			{Cmd: 32, Name: "NL80211_CMD_GET_SCAN"},
			{Cmd: 33, Name: "NL80211_CMD_TRIGGER_SCAN"},
			{Cmd: 34, Name: "NL80211_CMD_NEW_SCAN_RESULTS"},
			{Cmd: 35, Name: "NL80211_CMD_SCAN_ABORTED"},
			{Cmd: 36, Name: "NL80211_CMD_REG_CHANGE"},
			{Cmd: 37, Name: "NL80211_CMD_AUTHENTICATE"},
			{Cmd: 38, Name: "NL80211_CMD_ASSOCIATE"},
			{Cmd: 39, Name: "NL80211_CMD_DEAUTHENTICATE"},
			{Cmd: 40, Name: "NL80211_CMD_DISASSOCIATE"},
			{Cmd: 41, Name: "NL80211_CMD_MICHAEL_MIC_FAILURE"},
			{Cmd: 42, Name: "NL80211_CMD_REG_BEACON_HINT"},
			{Cmd: 43, Name: "NL80211_CMD_JOIN_IBSS"},
			{Cmd: 44, Name: "NL80211_CMD_LEAVE_IBSS"},
			{Cmd: 45, Name: "NL80211_CMD_TESTMODE"},
			{Cmd: 46, Name: "NL80211_CMD_CONNECT"},
			{Cmd: 47, Name: "NL80211_CMD_ROAM"},
			{Cmd: 48, Name: "NL80211_CMD_DISCONNECT"},
			{Cmd: 49, Name: "NL80211_CMD_SET_WIPHY_NETNS"},
			{Cmd: 50, Name: "NL80211_CMD_GET_SURVEY"},
			{Cmd: 51, Name: "NL80211_CMD_NEW_SURVEY_RESULTS"},
			{Cmd: 52, Name: "NL80211_CMD_SET_PMKSA"},
			{Cmd: 53, Name: "NL80211_CMD_DEL_PMKSA"},
			{Cmd: 54, Name: "NL80211_CMD_FLUSH_PMKSA"},
			{Cmd: 55, Name: "NL80211_CMD_REMAIN_ON_CHANNEL"},
			{Cmd: 56, Name: "NL80211_CMD_CANCEL_REMAIN_ON_CHANNEL"},
			{Cmd: 57, Name: "NL80211_CMD_SET_TX_BITRATE_MASK"},
			{Cmd: 58, Name: "NL80211_CMD_REGISTER_FRAME"},
			{Cmd: 59, Name: "NL80211_CMD_REGISTER_ACTION = NL80211_CMD_REGISTER_FRAME"},
			{Cmd: 60, Name: "NL80211_CMD_FRAME"},
			{Cmd: 61, Name: "NL80211_CMD_ACTION = NL80211_CMD_FRAME"},
			{Cmd: 62, Name: "NL80211_CMD_FRAME_TX_STATUS"},
			{Cmd: 63, Name: "NL80211_CMD_ACTION_TX_STATUS = NL80211_CMD_FRAME_TX_STATUS"},
			{Cmd: 64, Name: "NL80211_CMD_SET_POWER_SAVE"},
			{Cmd: 65, Name: "NL80211_CMD_GET_POWER_SAVE"},
			{Cmd: 66, Name: "NL80211_CMD_SET_CQM"},
			{Cmd: 67, Name: "NL80211_CMD_NOTIFY_CQM"},
			{Cmd: 68, Name: "NL80211_CMD_SET_CHANNEL"},
			{Cmd: 69, Name: "NL80211_CMD_SET_WDS_PEER"},
			{Cmd: 70, Name: "NL80211_CMD_FRAME_WAIT_CANCEL"},
			{Cmd: 71, Name: "NL80211_CMD_JOIN_MESH"},
			{Cmd: 72, Name: "NL80211_CMD_LEAVE_MESH"},
			{Cmd: 73, Name: "NL80211_CMD_UNPROT_DEAUTHENTICATE"},
			{Cmd: 74, Name: "NL80211_CMD_UNPROT_DISASSOCIATE"},
			{Cmd: 75, Name: "NL80211_CMD_NEW_PEER_CANDIDATE"},
			{Cmd: 76, Name: "NL80211_CMD_GET_WOWLAN"},
			{Cmd: 77, Name: "NL80211_CMD_SET_WOWLAN"},
			{Cmd: 78, Name: "NL80211_CMD_START_SCHED_SCAN"},
			{Cmd: 79, Name: "NL80211_CMD_STOP_SCHED_SCAN"},
			{Cmd: 80, Name: "NL80211_CMD_SCHED_SCAN_RESULTS"},
			{Cmd: 81, Name: "NL80211_CMD_SCHED_SCAN_STOPPED"},
			{Cmd: 82, Name: "NL80211_CMD_SET_REKEY_OFFLOAD"},
			{Cmd: 83, Name: "NL80211_CMD_PMKSA_CANDIDATE"},
			{Cmd: 84, Name: "NL80211_CMD_TDLS_OPER"},
			{Cmd: 85, Name: "NL80211_CMD_TDLS_MGMT"},
			{Cmd: 86, Name: "NL80211_CMD_UNEXPECTED_FRAME"},
			{Cmd: 87, Name: "NL80211_CMD_PROBE_CLIENT"},
			{Cmd: 88, Name: "NL80211_CMD_REGISTER_BEACONS"},
			{Cmd: 89, Name: "NL80211_CMD_UNEXPECTED_4ADDR_FRAME"},
			{Cmd: 90, Name: "NL80211_CMD_SET_NOACK_MAP"},
			{Cmd: 91, Name: "NL80211_CMD_CH_SWITCH_NOTIFY"},
			{Cmd: 92, Name: "NL80211_CMD_START_P2P_DEVICE"},
			{Cmd: 93, Name: "NL80211_CMD_STOP_P2P_DEVICE"},
			{Cmd: 94, Name: "NL80211_CMD_CONN_FAILED"},
			{Cmd: 95, Name: "NL80211_CMD_SET_MCAST_RATE"},
			{Cmd: 96, Name: "NL80211_CMD_SET_MAC_ACL"},
			{Cmd: 97, Name: "NL80211_CMD_RADAR_DETECT"},
			{Cmd: 98, Name: "NL80211_CMD_GET_PROTOCOL_FEATURES"},
			{Cmd: 99, Name: "NL80211_CMD_UPDATE_FT_IES"},
			{Cmd: 100, Name: "NL80211_CMD_FT_EVENT"},
			{Cmd: 101, Name: "NL80211_CMD_CRIT_PROTOCOL_START"},
			{Cmd: 102, Name: "NL80211_CMD_CRIT_PROTOCOL_STOP"},
			{Cmd: 103, Name: "NL80211_CMD_GET_COALESCE"},
			{Cmd: 104, Name: "NL80211_CMD_SET_COALESCE"},
			{Cmd: 105, Name: "NL80211_CMD_CHANNEL_SWITCH"},
			{Cmd: 106, Name: "NL80211_CMD_VENDOR"},
			{Cmd: 107, Name: "NL80211_CMD_SET_QOS_MAP"},
			{Cmd: 108, Name: "NL80211_CMD_ADD_TX_TS"},
			{Cmd: 109, Name: "NL80211_CMD_DEL_TX_TS"},
			{Cmd: 110, Name: "NL80211_CMD_GET_MPP"},
			{Cmd: 111, Name: "NL80211_CMD_JOIN_OCB"},
			{Cmd: 112, Name: "NL80211_CMD_LEAVE_OCB"},
			{Cmd: 113, Name: "NL80211_CMD_CH_SWITCH_STARTED_NOTIFY"},
			{Cmd: 114, Name: "NL80211_CMD_TDLS_CHANNEL_SWITCH"},
			{Cmd: 115, Name: "NL80211_CMD_TDLS_CANCEL_CHANNEL_SWITCH"},
			{Cmd: 116, Name: "NL80211_CMD_WIPHY_REG_CHANGE"},
			{Cmd: 117, Name: "NL80211_CMD_ABORT_SCAN"},
			{Cmd: 118, Name: "NL80211_CMD_START_NAN"},
			{Cmd: 119, Name: "NL80211_CMD_STOP_NAN"},
			{Cmd: 120, Name: "NL80211_CMD_ADD_NAN_FUNCTION"},
			{Cmd: 121, Name: "NL80211_CMD_DEL_NAN_FUNCTION"},
			{Cmd: 122, Name: "NL80211_CMD_CHANGE_NAN_CONFIG"},
			{Cmd: 123, Name: "NL80211_CMD_NAN_MATCH"},
			{Cmd: 124, Name: "NL80211_CMD_SET_MULTICAST_TO_UNICAST"},
			{Cmd: 125, Name: "NL80211_CMD_UPDATE_CONNECT_PARAMS"},
			{Cmd: 126, Name: "NL80211_CMD_SET_PMK"},
			{Cmd: 127, Name: "NL80211_CMD_DEL_PMK"},
			{Cmd: 128, Name: "NL80211_CMD_PORT_AUTHORIZED"},
			{Cmd: 129, Name: "NL80211_CMD_RELOAD_REGDB"},
			{Cmd: 130, Name: "NL80211_CMD_EXTERNAL_AUTH"},
			{Cmd: 131, Name: "NL80211_CMD_STA_OPMODE_CHANGED"},
			{Cmd: 132, Name: "NL80211_CMD_CONTROL_PORT_FRAME"},
			{Cmd: 133, Name: "NL80211_CMD_GET_FTM_RESPONDER_STATS"},
			{Cmd: 134, Name: "NL80211_CMD_PEER_MEASUREMENT_START"},
			{Cmd: 135, Name: "NL80211_CMD_PEER_MEASUREMENT_RESULT"},
			{Cmd: 136, Name: "NL80211_CMD_PEER_MEASUREMENT_COMPLETE"},
			{Cmd: 137, Name: "NL80211_CMD_NOTIFY_RADAR"},
			{Cmd: 138, Name: "NL80211_CMD_UPDATE_OWE_INFO"},
			{Cmd: 139, Name: "NL80211_CMD_PROBE_MESH_LINK"},
			{Cmd: 140, Name: "NL80211_CMD_SET_TID_CONFIG"},
			{Cmd: 141, Name: "NL80211_CMD_UNPROT_BEACON"},
			{Cmd: 142, Name: "NL80211_CMD_CONTROL_PORT_FRAME_TX_STATUS"},
			{Cmd: 143, Name: "NL80211_CMD_SET_SAR_SPECS"},
			{Cmd: 144, Name: "NL80211_CMD_OBSS_COLOR_COLLISION"},
			{Cmd: 145, Name: "NL80211_CMD_COLOR_CHANGE_REQUEST"},
			{Cmd: 146, Name: "NL80211_CMD_COLOR_CHANGE_STARTED"},
			{Cmd: 147, Name: "NL80211_CMD_COLOR_CHANGE_ABORTED"},
			{Cmd: 148, Name: "NL80211_CMD_COLOR_CHANGE_COMPLETED"},
			{Cmd: 149, Name: "NL80211_CMD_SET_FILS_AAD"},
			{Cmd: 150, Name: "NL80211_CMD_ASSOC_COMEBACK"},
			{Cmd: 151, Name: "NL80211_CMD_ADD_LINK"},
			{Cmd: 152, Name: "NL80211_CMD_REMOVE_LINK"},
			{Cmd: 153, Name: "NL80211_CMD_ADD_LINK_STA"},
			{Cmd: 154, Name: "NL80211_CMD_MODIFY_LINK_STA"},
			{Cmd: 155, Name: "NL80211_CMD_REMOVE_LINK_STA"},
			{Cmd: 156, Name: "NL80211_CMD_SET_HW_TIMESTAMP"},
			{Cmd: 157, Name: "NL80211_CMD_LINKS_REMOVED"},
			{Cmd: 158, Name: "NL80211_CMD_SET_TID_TO_LINK_MAPPING"},
			{Cmd: 159, Name: "NL80211_CMD_ASSOC_MLO_RECONF"},
			{Cmd: 160, Name: "NL80211_CMD_EPCS_CFG"},
			{Cmd: 161, Name: "NL80211_CMD_NAN_NEXT_DW_NOTIFICATION"},
			{Cmd: 162, Name: "NL80211_CMD_NAN_CLUSTER_JOINED"},
			{Cmd: 163, Name: "NL80211_CMD_INCUMBENT_SIGNAL_DETECT"},
			{Cmd: 164, Name: "NL80211_CMD_NAN_SET_LOCAL_SCHED"},
			{Cmd: 165, Name: "NL80211_CMD_NAN_SCHED_UPDATE_DONE"},
			{Cmd: 166, Name: "NL80211_CMD_NAN_SET_PEER_SCHED"},
			{Cmd: 167, Name: "NL80211_CMD_NAN_ULW_UPDATE"},
			{Cmd: 168, Name: "NL80211_CMD_NAN_CHANNEL_EVAC"},
			{Cmd: 169, Name: "NL80211_CMD_START_PD"},
			{Cmd: 170, Name: "NL80211_CMD_STOP_PD"},
		},
	},
	{
		Name: "nlctrl",
		Desc: "genetlink meta-family that exposes information about all genetlink families registered in the kernel (including itself).", //nolint
		Cmds: []Cmd{
			{Cmd: 3, Name: "CTRL_CMD_GETFAMILY"},
			{Cmd: 10, Name: "CTRL_CMD_GETPOLICY"},
		},
	},
	{
		Name: "ovpn",
		Desc: "Netlink protocol to control OpenVPN network device",
		Cmds: []Cmd{
			{Cmd: 1, Name: "OVPN_CMD_PEER_NEW"},
			{Cmd: 2, Name: "OVPN_CMD_PEER_SET"},
			{Cmd: 3, Name: "OVPN_CMD_PEER_GET"},
			{Cmd: 4, Name: "OVPN_CMD_PEER_DEL"},
			{Cmd: 5, Name: "OVPN_CMD_PEER_DEL_NTF"},
			{Cmd: 6, Name: "OVPN_CMD_KEY_NEW"},
			{Cmd: 7, Name: "OVPN_CMD_KEY_GET"},
			{Cmd: 8, Name: "OVPN_CMD_KEY_SWAP"},
			{Cmd: 9, Name: "OVPN_CMD_KEY_SWAP_NTF"},
			{Cmd: 10, Name: "OVPN_CMD_KEY_DEL"},
			{Cmd: 11, Name: "OVPN_CMD_PEER_FLOAT_NTF"},
		},
	},
	{
		Name: "SEG6",
		Desc: "SR-IPv6 implementation",
		Cmds: []Cmd{
			{Cmd: 1, Name: "SEG6_CMD_SETHMAC"},
			{Cmd: 2, Name: "SEG6_CMD_DUMPHMAC"},
			{Cmd: 3, Name: "SEG6_CMD_SET_TUNSRC"},
			{Cmd: 4, Name: "SEG6_CMD_GET_TUNSRC"},
		},
	},
	{
		Name: "TASKSTATS",
		Desc: "Taskstats is a netlink-based interface for sending per-task and per-process statistics from the kernel to userspace.", //nolint
		Cmds: []Cmd{
			{Cmd: 1, Name: "TASKSTATS_CMD_GET"},
			{Cmd: 2, Name: "TASKSTATS_CMD_NEW"},
		},
	},
	{
		Name: "tcp_metrics",
		Desc: "Management interface for TCP metrics.",
		Cmds: []Cmd{
			{Cmd: 1, Name: "TCP_METRICS_CMD_GET"},
			{Cmd: 2, Name: "TCP_METRICS_CMD_DEL"},
		},
	},
	{
		Name: "team",
		Cmds: []Cmd{
			{Cmd: 0, Name: "TEAM_CMD_NOOP"},
			{Cmd: 1, Name: "TEAM_CMD_OPTIONS_SET"},
			{Cmd: 2, Name: "TEAM_CMD_OPTIONS_GET"},
			{Cmd: 3, Name: "TEAM_CMD_PORT_LIST_GET"},
		},
	},
	{
		Name: "wireguard",
		Desc: "Netlink protocol to control WireGuard network devices.",
		Cmds: []Cmd{
			{Cmd: 0, Name: "WG_CMD_GET_DEVICE"},
			{Cmd: 1, Name: "WG_CMD_SET_DEVICE"},
		},
	},
}
